version: "3.9"
services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=arnhem
      - DB_USER=arnhem
      - DB_PASSWORD=password
    depends_on:
      - db
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
  db:
    image: postgres:13
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=arnhem
      - POSTGRES_USER=arnhem
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
