version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "poetry run python manage.py migrate --skip-checks &&
      poetry run python manage.py collectstatic --no-input &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
